<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJgi20nb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJgi20nb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJgi20nb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJgi20nb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJgi20nb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jgi20nb',
    'container.build_id' => '1469c341',
    'container.build_time' => 1584979526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJgi20nb');
